name: test

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type:
          - osxcross
        variant:
          - ubuntu
          - debian
          - alpine
        include:
          - type: osxsdk
            variant: alpine
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Test
        uses: docker/bake-action@v6
        with:
          source: "{{defaultContext}}"
          targets: test-${{ matrix.type }}
          set: |
            *.cache-from=type=gha,scope=${{ matrix.variant }}-linux-amd64
        env:
          BASE_VARIANT: ${{ matrix.variant }}
